[package]
name = "aliasmgr-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
aliasmgr-core = { path = "../aliasmgr-core" }
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
atty = "0.2"

[lib]
path = "src/lib.rs"

[[bin]]
name = "aliasmgr"
path = "src/main.rs"
