name: CI

on:
  push:
    paths-ignore: ["**/*.md"]
  pull_request:
    paths-ignore: ["**/*.md"]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - run: cargo fmt --check
      - run: cargo clippy --workspace --all-targets -- -D warnings
  test-linux:
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --workspace
  test-windows:
    runs-on: windows-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: dtolnay/rust-toolchain@stable
      - name: PowerShell 5.1 version
        shell: powershell
        run: $PSVersionTable.PSVersion.ToString()
      - name: PowerShell 7 version
        shell: pwsh
        run: $PSVersionTable.PSVersion.ToString()
      - run: cargo test --workspace
